nginx:
    build: nginx
    links:
        - fusiondirectory
    volumes_from:
        - gitlab
    ports:
        - "80:80"
        - "8080:8080"
        - "8081:8081"
    volumes:
        - nginx/config/sites-enabled:/etc/nginx/sites-enabled
        - nginx/data/www:/var/www
openldap:
    build: openldap
    ports:
        - "127.0.0.1:389:389"
    volumes:
        - /var/lib/ldap/
fusiondirectory:
    build: fusiondirectory
    links:
        - openldap
    volumes:
        - fusiondirectory/config/sites-enabled:/etc/apache2/sites-enabled
        - fusiondirectory/config/fusiondirectory:/etc/fusiondirectory
    expose:
        - 80
postgres:
    build: postgres
    ports:
        - "127.0.0.1:5432:5432"
    volumes:
        - /var/lib/postgresql
redis:
    build: redis
    volumes:
        - redis/config/:/redis_conf
        - /var/lib/redis
    ports:
        - "127.0.0.1:6379:6379"
gitlab:
    build: gitlab
    links:
        - openldap
        - postgres
        - redis
    volumes:
        - gitlab/config/:/gitlab_config
        - /home/git/gitlab/public
        - /home/git/gitlab/tmp/sockets/
        - /home/git/repositories/
        - /home/git/gitlab-satellites/
        - /home/git/.ssh/
    ports:
        - "127.0.0.1:2222:22"
